### ISSUE TITLE
mqueue test program

### ISSUE THREAD

**Issue by skliper** [nasa/osal#229]
OSAL should include a simple mqueue test program to validate that the user has the correct settings and permissions to create/open/close/delete mqueues. Often users stumble on mqueue configuration and it is more difficult to diagnose when it's wrapped in the entirety of OSAL/cFS.

**Comment by skliper** [comment]
_Imported from trac issue 206.  Created by cdknight on 2018-11-16T19:04:20, last modified: 2019-08-14T14:11:46_

**Comment by jphickey** [comment]
Rather than making a whole new test program, there is already a "queue-timeout-test" test program that does much of this.  

Right now this test program only focuses on calling OS_QueueCreate() followed by OS_QueueGet() and getting the timeout response.  But it shouldn't be too hard to just add another test case to this, to actually call OS_QueuePut() to send some test data into the queue and validate it on the other side.

Furthermore, the ut_oscore_queue_test does a much more extensive test of the OS_QueuePut/OS_QueueGet functions, but it is a bit convoluted and doesn't use the same framework.

**Comment by skliper** [comment]
Preference is to add test or add to existing test (queue-timeout-test) using the utassert framework.  Either approach is fine (if you want to keep queue-timeout-test specific to timeouts and add a test for general queue behavior, or if you want to generalize the existing test to cover more functionality).  

Expending resources on the "unit-tests" that use the alternate framework is discouraged.  Eventually the "scenarios" covered by these tests should all be covered by the utassert tests.
