### ISSUE TITLE
OSAL network APIs missing functional tests

### ISSUE THREAD

**Issue by CDKnightNASA** [nasa/osal#373]
**Is your feature request related to a problem? Please describe.**
Seems there's not really any unit tests for the OSAL networking code.

**Describe the solution you'd like**
Should have unit tests.

**Describe alternatives you've considered**
Not having unit tests?

**Additional context**
Note that to do unit testing, it's likely we'll need to stub out OS-provided API's (open, select, socket, bind, accept, close().) Do we have a standard framework for stubbing out OS-provided functions?

**Requester Info**
Christopher.D.Knight@nasa.gov

**Comment by CDKnightNASA** [comment]
No code yet, but would like to discuss at the CCB as to whether to stub out OS functions or otherwise how to test.

**Comment by jphickey** [comment]
As noted in the CCB, there are two flavors of testing to consider:
1. Functional
2. Coverage

In OSAL the "tests" and "unit-tests" are functional tests (type 1).  These do _NOT_ use stubs., they use the real OSAL, linked to the real C library  We can (and should) write some new tests that exercise the network socket API.  We can create two threads, which talk to eachother via IP sockets that are bound to the localhost address (127.0.0.1).

OSAL also has coverage tests (type 2) but these are mainly to validate the error checking and other items which cannot typically be reached in the functional test.  This links each OSAL unit with stubs, including stubs for the C library calls.  Yes we have a framework for doing this, and the "shared" layer (including the network) should be covered by it already.  However the "impl" part probably needs better coverage, because only VxWorks is done 100% (that's a separate issue though).

**Comment by skliper** [comment]
Concur, definitely need to add functional tests as Joe suggests.

**Comment by skliper** [comment]
Missing tests for all of the following:
OS_SocketAddrInit, OS_SocketAddrToString, OS_SocketAddrFromString, OS_SocketAddrGetPort, OS_SocketAddrSetPort
OS_SocketOpen, OS_SocketBind, OS_SocketConnect, OS_SocketAccept, OS_SocketRecvFrom, OS_SocketSendTo, OS_SocketGetIdByName, OS_SocketGetInfo

Certification issue.

**Comment by astrogeco** [comment]
CCB 2020-03-25: Will go ahead with this. It is a priority.
