### ISSUE TITLE
OSAL Select APIs missing functional test

### ISSUE THREAD

**Issue by skliper** [nasa/osal#377]
**Is your feature request related to a problem? Please describe.**
OS_SelectMultipe, OS_SelectSingle, OS_SelectFdZero, OS_SelectFdAdd, OS_SelectFdClear, OS_SelectFdIsSet all missing functional tests

**Describe the solution you'd like**
Add tests

**Describe alternatives you've considered**
None

**Additional context**
Certification issue.

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by CDKnightNASA** [comment]
I'll start taking a crack at this.

**Comment by CDKnightNASA** [comment]
will wait for #405 to be merged into master and will use new macros, plus need to rebase and remerge the code from #391 and #392

**Comment by skliper** [comment]
This was closed by mistake, Select APIs still need a test to show they function correctly

**Comment by jphickey** [comment]
FYI - there _IS_ now some unit test code which calls "select" .... 

I have to make a change in the select API anyway to fix a different bug (#453), and change I'm making for that issue also requires some updates to these test cases.  This is actually how the bug was noticed -- running this test on RTEMS caused failure.

**Comment by skliper** [comment]
TODO - check if #462 is sufficient to satisfy the unit test standards.
