### ISSUE TITLE
TimeBase API missing functional tests

### ISSUE THREAD

**Issue by skliper** [nasa/osal#380]
**Is your feature request related to a problem? Please describe.**
OS_TimeBaseCreate, OS_TimeBaseSet, OS_TimeBaseDelete, OS_TimeBaseGetIdByName, OS_TimeBaseGetInfo, OS_TimeBaseGetFreeRun all missing functional tests

**Describe the solution you'd like**
Add tests

**Describe alternatives you've considered**
None

**Additional context**
Certification Issue

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by yammajamma** [comment]
I can take this.

**Comment by jphickey** [comment]
Note that a time base object exists primarily to underpin the timer objects, and they aren't used directly by apps.  Therefore API is used and invoked, either directly or indirectly, as part of the existing timer tests.  I'm also not sure how you could even test it in isolation, because these objects aren't used directly.  Aside from simply creating/deleting the objIDs and just confirming this works?

**Comment by skliper** [comment]
It's basically to meet the formal test requirements for certification, test full parameter ranges, etc.

**Comment by jphickey** [comment]
Yeah, most of that parameter checking is already in the coverage test, but could be done again in a full-stack/non-stub enviornment.  

I guess the other thing is to confirm you can create e.g.  up to `OS_MAX_TIMEBASES` objects and the +1 one fails, and also that you can delete them successfully too?

**Comment by skliper** [comment]
Yes please (create all, delete all)!  Note we don't get to take verification credit from a coverage test.  So the parameter checking needs to be done in the functional test.
