### ISSUE TITLE
Unreachable code in posix OS_BinSemCreate_Impl

### ISSUE THREAD

**Issue by skliper** [nasa/osal#803]
**Is your feature request related to a problem? Please describe.**
Can't reach:
https://github.com/nasa/osal/blob/09a2c5e793639e508174a2446989274acf36f25e/src/os/posix/src/os-impl-binsem.c#L217-L220

**Describe the solution you'd like**
Refactor to eliminate dead code.

**Describe alternatives you've considered**
None

**Additional context**
Static analysis warning

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by jphickey** [comment]
This a matter of order-of-operations - nothing can currently fail after the condition var is created, but that's just the current form.  

Although unreachable _right now_ if something gets added in the future (e.g. setting an attribute or something after the cond was created) then this will become relevant/possible to reach this again.  So I wouldn't necessarily recommend removing this - as it is a bit of future-proofing -  a change elsewhere in the function can easily make it reachable again.

Rather than removing I would suggest adding something else - such as a "test" call to `pthread_cond_signal()` - and check the status (should _always_ be successful on a cond var that was just created, and a no-op because nothing is pending).  So this should always succeed, but it will provide a theoretical path where the cleanup has to do both - so it won't be flagged as unreachable anymore.
