### ISSUE TITLE
Either deprecated or require OS_TaskRegister

### ISSUE THREAD

**Issue by skliper** [nasa/osal#853]
**Is your feature request related to a problem? Please describe.**
OS_TaskRegister has comments that it is obsolete, but never got officially deprecated.

**Describe the solution you'd like**
Need to either officially deprecate or officially support.

**Describe alternatives you've considered**
None

**Additional context**
Impacts apps, better now in a major release than later for removal.

**Requester Info**
Jacob Hageman - NASA/GSFC, OSAL code review

**Comment by jphickey** [comment]
My vote would be to deprecate if we must do something.  

@ejtimmon  can you confirm if any GSFC apps are currently calling `OS_TaskRegister()`?

Grepping the copies that I have locally, I don't see any current references to `OS_TaskRegister`.  So it seems like we should be able to remove, but I'm not sure.

Historically - old (last-gen) OSAL would directly/immediately invoke the application-specified entry point of a new task.  In order to update the internal structures, there was then a requirement that the user application calls "OS_TaskRegister()" to complete the registration process so OSAL could update its globals and track the state of the new task, and make it so e.g. OS_TaskGetID() would work correctly, etc.

Now, in the current design - OSAL invokes the application-specified entry point via a wrapper, and this wrapper performs all registration(s) that must be done in the context of the new task.  Therefore all global table/state updates are already done before the entry point is even called, and OS_TaskGetID() and other functions work immediately with no extra action required on the application side.

This design is both simpler and less error prone (no chance of forgetting to call register/indeterminate state/half-initialized entries, etc).  OSAL does this on all platforms.  So I cannot think of a reason why one would want to go back to the old design of having an extra function that must be explicitly called by the user application in its entry point function.  Or put another way, I can't think of any initialization actions that couldn't be handled in the wrapper that runs before invoking the entry point, such that we would ever need to revive/use this function.

Unless someone can think of a use-case where some initialization bits can only be done via something like OS_TaskRegister() and cannot be done before calling the entry point?  I can't....
