### ISSUE TITLE
Impossible to test OS_CONSOLE_ASYNC false case

### ISSUE THREAD

**Issue by skliper** [nasa/osal#957]
**Is your feature request related to a problem? Please describe.**
Now that OS_CONSOLE_ASYNC is defined locally, it's impossible to functionally test false case or get full branch coverage on `OS_ConsoleCreate_Impl` without modifying the code under test:
https://github.com/nasa/osal/blob/ba0ac40d3b58b4d12f32a2222c8c8ed2fb663c65/src/os/vxworks/src/os-impl-console.c#L41-L48

https://github.com/nasa/osal/blob/ba0ac40d3b58b4d12f32a2222c8c8ed2fb663c65/src/os/vxworks/src/os-impl-console.c#L146-L148

**Describe the solution you'd like**
Either need to be able to exercise this option or remove it.

**Describe alternatives you've considered**
None

**Additional context**
Prevents full branch coverage

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by jphickey** [comment]
I'm trying to recall why this was removed from osconfig.h ... It is still relevant/preferable to run in this mode for debugging situations.  Many times OS_printf is used for debugging and if the actual output is decoupled, it can change the order with which things appear.  It also saves the memory cost of another task+stack in constrained environments.

If I understand correctly the issue here is limited to the "create_impl" function only - since it can't easily be tested with the flag as false.  Maybe a compromise solution would be to move the boolean from the impl layer to the shared layer, which would allow the impl coverage test to set it both ways at least.

**Comment by skliper** [comment]
I'd rather make it an option that can be tested functionally or remove it.  Coverage testing with overrides doesn't prove all the logic works together.

Option - ifndef make it async=true.

**Comment by skliper** [comment]
Or relate it to OS_DEBUG or similar, and/or note the expected context/reasoning.

**Comment by jphickey** [comment]
I consider it similar to the shell switch or something like that - for FSW the user chooses which way to configure it and then it gets compiled in that config, but for coverage test - due to the design and its "backdoor" methods of running things directly, it can still test it both ways, regardless of how its configured in FSW.

Right now even that's not possible because of the proximity to the definition and the runtime check.  If they were in separate units, this would be easily doable.

Can also resurrect this as an osconfig option.  As I said, I don't recall why it was removed, but might have been before osconfig.h was converted to osconfig.cmake.  In the current design there shouldn't be a problem of having this option, and defaulting it to true.

I'd rather not tie it to OS_DEBUG - although that's one justification for changing it - simply saving the cost of an extra task+stack might be worthwhile to some users.
